views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - NAMESPACE
      - NAME
      - PF
      - READY|S
      - STATUS|S
      - RESTARTS
      - CPU
      - MEM
      - '%CPU/R'
      - '%CPU/L'
      - '%MEM/R'
      - '%MEM/L'
      - IP|S
      - NODE
      - AGE
      # Support 'super column blow' 0.50.0 and later
      - IMAGE VERSION:.spec.containers[0].image|split(":")|.[-1]|RS
  
  velero.io/v1/schedules:
    sortColumn: AGE:asc
    columns:
      - NAMESPACE
      - NAME
      - STATUS
      - SCHEDULE
      - TTL:.spec.template.ttl|S
      - LASTBACKUP
      - PAUSED
      - LOCATION:.spec.template.storageLocation|S
      - AGE
  
  velero.io/v1/backupstoragelocations:
    sortColumn: AGE:asc
    columns:
      - NAMESPACE
      - NAME
      - STORAGE REGION:.spec.config.region|S
      - STORAGE NAME:.spec.objectStorage.bucket|S
      - PHASE
      - LAST VALIDATED
      - DEFAULT
      - AGE
