plugin:
  get-all:
    shortCut: g
    confirm: false
    description: "Get all resource in namespace"
    scopes:
      - all
    command: sh
    background: false
    args:
      - -c
      - "kubectl -n $NAMESPACE get all | less"

  tree:
    shortCut: t
    confirm: false
    description: "Switch to the tree view"
    scopes:
      - all
    command: sh
    background: false
    args:
      - -i
      - -c
      - "kubectl tree -n $NAMESPACE $RESOURCE_NAME $NAME --context $CONTEXT && tail -f /dev/null"
